---
# NTP
- name: Install NTP
  apt:
	name: ntp
	state: present

- name: Start and enable NTP service
  service:
	name: ntp
	state: started
	enabled: yes

# Open Stack
- name: Install python3-openstackclient
  apt:
	name: python3-openstackclient
	state: present

- name: Add OpenStack Cloud Archive Repository
  apt_repository:
	repo: "deb http://ubuntu-cloud.archive.canonical.com/ubuntu {{ ansible_distribution_release }} main"
	state: present

- name: Update apt cache
  apt:
	update_cache: yes

- name: Update apt cache
  apt:
	update_cache: yes

# SQL Database
- name: Install MariaDB and Python packages
  apt:
	name: "{{ item }}"
	state: present
  loop:
	- mariadb-server
	- python3-pymysql

- name: Install MariaDB and Python packages
  apt:
	name: "{{ item }}"
	state: present
  loop:
	- mariadb-server
	- python3-mysqldb

- name: Ensure the directory structure exists for MariaDB configuration file
  file:
	path: /etc/mysql/mariadb.conf.d
	state: directory

- name: Create the MariaDB configuration file
  copy:
	dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
	content: |
  	[mysqld]
  	bind-address = 10.0.0.11
  	default-storage-engine = innodb
  	innodb_file_per_table = on
  	max_connections = 4096
  	collation-server = utf8_general_ci
  	character-set-server = utf8
 	 
# Message Queue
- name: Install RabbitMQ package
  apt:
	name: rabbitmq-server
	state: present
  become: true

- name: Set permissions for openstack user
  shell: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
  become: true

- name: Restart RabbitMQ service
  service:
	name: rabbitmq-server
	state: restarted
  become: true
 
# Memcached
- name: Install Memcached and Python3 Memcache library
  apt:
	name:
  	- memcached
  	- python3-memcache
	state: present

- name: Configure Memcached to use management IP address
  lineinfile:
	path: /etc/memcached.conf
	line: "-l 10.0.0.11"
  notify: Restart Memcached
 
# ETCD
- name: Enable Universe repository
  apt_repository:
	repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_lsb.codename }} universe"
	state: present

- name: Install etcd package
  apt:
	name: etcd
	state: present

- name: Configure etcd
  template:
	src: roles/ubuntu_openstack/templates/etcd_config.j2
	dest: /etc/default/etcd

- name: Restart etcd
  service:
	name: etcd
	state: restarted
